---
output:
  word_document: default
  html_document: default
---
There are 25 variables:

# Predictors
-> ID: ID of each client
-> LIMIT_BAL: Amount of given credit in NT dollars (includes individual and family/supplementary credit
-> SEX: Gender (1=male, 2=female)
-> EDUCATION: (1=graduate school, 2=university, 3=high school, 4=others, 5=unknown, 6=unknown)
-> MARRIAGE: Marital status (1=married, 2=single, 3=others)
-> AGE: Age in years
-> PAY_1: Repayment status in September, 2005 (-1=pay duly, 1=payment delay for one month,   2=payment delay for two months, ... 8=payment delay for eight months, 9=payment delay for nine months and above)
-> PAY_2: Repayment status in August, 2005 (scale same as above)
-> PAY_3: Repayment status in July, 2005 (scale same as above)
-> PAY_4: Repayment status in June, 2005 (scale same as above)
-> PAY_5: Repayment status in May, 2005 (scale same as above)
-> PAY_6: Repayment status in April, 2005 (scale same as above)
-> BILL_AMT1: Amount of bill statement in September, 2005 (NT dollar)
-> BILL_AMT2: Amount of bill statement in August, 2005 (NT dollar)
-> BILL_AMT3: Amount of bill statement in July, 2005 (NT dollar)
-> BILL_AMT4: Amount of bill statement in June, 2005 (NT dollar)
-> BILL_AMT5: Amount of bill statement in May, 2005 (NT dollar)
-> BILL_AMT6: Amount of bill statement in April, 2005 (NT dollar)
-> PAY_AMT1: Amount of previous payment in September, 2005 (NT dollar)
-> PAY_AMT2: Amount of previous payment in August, 2005 (NT dollar)
-> PAY_AMT3: Amount of previous payment in July, 2005 (NT dollar)
-> PAY_AMT4: Amount of previous payment in June, 2005 (NT dollar)
-> PAY_AMT5: Amount of previous payment in May, 2005 (NT dollar)
-> PAY_AMT6: Amount of previous payment in April, 2005 (NT dollar)

# Response
-> default.payment.next.month: Default payment (1=yes, 0=no)

# Variables
 [1] "ID"            "LIMIT_BAL"     "SEX"           "EDUCATION"     "MARRIAGE"      "AGE"        
 [7] "PAY_1"         "PAY_2"         "PAY_3"         "PAY_4"         "PAY_5"         "PAY_6"        
[13] "BILL_AMT1"     "BILL_AMT2"     "BILL_AMT3"     "BILL_AMT4"     "BILL_AMT5"     "BILL_AMT6"    
[19] "PAY_AMT1"      "PAY_AMT2"      "PAY_AMT3"      "PAY_AMT4"      "PAY_AMT5"      "PAY_AMT6"     
[25] "DEFAULT"       "GENDER"        "MARITALSTATUS"

# Numerical
1. ID
2. LIMIT_BAL
6. AGE
7. PAY_1
8. PAY_2
9. PAY_3
10. PAY_4
11. PAY_5
12. PAY_6
13. BILL_AMT1
14. BILL_AMT2
15. BILL_AMT3
16. BILL_AMT4
17. BILL_AMT5
18. BILL_AMT6
19. PAY_AMT1
20. PAY_AMT2
21. PAY_AMT3
22. PAY_AMT4
23. PAY_AMT5
24. PAY_AMT6

# FACTORS
3. SEX - 0, 1
4. EDUCATION - 1, 2, 3, 4
5. MARRIAGE - 0, 1, 2
25*. DEFAULT - 0, 1

# CHARACTERS
26. GENDER - MALE, FEMALE
27. MARITAL STATUS - MARRIED, NOT MARRIED, OTHERS

educ_1 = count(our.data[our.data$EDUCATION == 1, ], vars = "DEFAULT")
educ_2 = count(our.data[our.data$EDUCATION == 2, ], vars = "DEFAULT")
educ_3 = count(our.data[our.data$EDUCATION == 3, ], vars = "DEFAULT")
educ_4 = count(our.data[our.data$EDUCATION == 4, ], vars = "DEFAULT")


#################
str(our.data)
'data.frame':	30000 obs. of  30 variables:
 1. $ ID                     : int  1 2 3 4 5 6 7 8 9 10 ...
 2. $ LIMIT_BAL              : num  20000 120000 90000 50000 50000 50000 500000 100000 140000 20000 ...
 3. $ SEX                    : Factor w/ 2 levels "1","2": 2 2 2 2 1 1 1 2 2 1 ...
 4. $ EDUCATION              : Factor w/ 4 levels "1","2","3","4": 2 2 2 2 2 1 1 2 3 3 ...
 5. $ MARRIAGE               : Factor w/ 3 levels "0","1","2": 2 3 3 2 2 3 3 3 2 3 ...
 6. $ AGE                    : int  24 26 34 37 57 37 29 23 28 35 ...
 7. $ PAY_1                  : Factor w/ 11 levels "-2","-1","0",..: 5 2 3 3 2 3 3 3 3 1 ...
 8. $ PAY_2                  : int  2 2 0 0 0 0 0 -1 0 -2 ...
 9. $ PAY_3                  : int  -1 0 0 0 -1 0 0 -1 2 -2 ...
 10. $ PAY_4                  : int  -1 0 0 0 0 0 0 0 0 -2 ...
 11. $ PAY_5                  : int  -2 0 0 0 0 0 0 0 0 -1 ...
 12. $ PAY_6                  : int  -2 2 0 0 0 0 0 -1 0 -1 ...
 13. $ BILL_AMT1              : num  3913 2682 29239 46990 8617 ...
 14. $ BILL_AMT2              : num  3102 1725 14027 48233 5670 ...
 15. $ BILL_AMT3              : num  689 2682 13559 49291 35835 ...
 16. $ BILL_AMT4              : num  0 3272 14331 28314 20940 ...
 17. $ BILL_AMT5              : num  0 3455 14948 28959 19146 ...
 18. $ BILL_AMT6              : num  0 3261 15549 29547 19131 ...
 19. $ PAY_AMT1               : num  0 0 1518 2000 2000 ...
 20. $ PAY_AMT2               : num  689 1000 1500 2019 36681 ...
 21. $ PAY_AMT3               : num  0 1000 1000 1200 10000 657 38000 0 432 0 ...
 22. $ PAY_AMT4               : num  0 1000 1000 1100 9000 ...
 23. $ PAY_AMT5               : num  0 0 1000 1069 689 ...
 24. $ PAY_AMT6               : num  0 2000 5000 1000 679 ...
 25. $ DEFAULT                : Factor w/ 2 levels "0","1": 2 2 1 1 1 1 1 1 1 1 ...
 26. $ GENDER                 : chr  "Female" "Female" "Female" "Female" ...
 27. $ MARITALSTATUS          : Factor w/ 3 levels "Married","Not Married",..: 1 2 2 1 1 2 2 2 1 2 ...
 28. $ REMAINING_AMT_PER      : num  91.1 70.7 89.2 96.4 46 ...
 29. $ REMAINING_AMT_PER_RANGE: Factor w/ 11 levels "-1","0","1","2",..: 11 9 10 11 6 11 11 8 10 6 ...
 30. $ LIMIT_BAL_SEG          : Factor w/ 10 levels "0","1","2","3",..: 2 3 2 2 2 2 6 2 3 2 ...
